//! Where references are declared: resolution against a workspace
//! ([`structurizr_query::reference`]) joined with the parser's source
//! locations. Shared by `structurizrx locate` and
//! `GET /api/workspace/{name}/locate`, so both report the same things in the
//! same JSON shape.

use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};

use serde_json::{json, Value};
use structurizr_dsl::{SourceLocation, SourceLocations};
use structurizr_query::reference::{
    parse_reference, Catalog, Miss, MissKind, RelationshipMatch, Target,
};

/// One place to show for a target, and why it is the place when that is not
/// obvious (a replicated or implied relationship).
pub struct Place {
    pub location: SourceLocation,
    pub note: Option<String>,
}

pub struct Item {
    pub reference: String,
    pub target: Target,
    pub places: Vec<Place>,
    /// Why there are no places, when there are none.
    pub note: Option<String>,
}

pub struct Located {
    pub items: Vec<Item>,
    /// (reference, why it resolved to nothing)
    pub misses: Vec<(String, Miss)>,
}

/// Resolve each reference and find where every target is declared.
/// `locations` is `None` for a `.json` workspace; `generated` holds the keys
/// of views generated by `auto`, which have no statement of their own.
pub fn locate(
    catalog: &Catalog,
    locations: Option<&SourceLocations>,
    generated: &HashSet<String>,
    references: &[String],
) -> Located {
    let mut located = Located {
        items: Vec::new(),
        misses: Vec::new(),
    };
    for reference in references {
        match catalog.resolve(&parse_reference(reference)) {
            Ok(targets) => {
                for target in targets {
                    let (places, note) = places_for(&target, locations, generated);
                    located.items.push(Item {
                        reference: reference.clone(),
                        target,
                        places,
                        note,
                    });
                }
            }
            Err(miss) => located.misses.push((reference.clone(), miss)),
        }
    }
    located
}

/// `{items: [...], unresolved: [...]}`, as printed by `locate --json`.
pub fn to_json(located: &Located) -> Value {
    let mut sources = SourceLines::default();
    let mut items = Vec::new();
    for item in &located.items {
        let mut v = target_json(&item.target);
        v["reference"] = json!(item.reference);
        v["locations"] = Value::Array(
            item.places
                .iter()
                .map(|p| place_json(p, &mut sources))
                .collect(),
        );
        v["note"] = json!(item.note);
        items.push(v);
    }
    json!({
        "items": items,
        "unresolved": located.misses.iter().map(|(reference, miss)| json!({
            "reference": reference,
            "message": miss_message(miss),
            "suggestion": suggestion(miss),
        })).collect::<Vec<_>>(),
    })
}

fn places_for(
    target: &Target,
    locations: Option<&SourceLocations>,
    generated: &HashSet<String>,
) -> (Vec<Place>, Option<String>) {
    let Some(locations) = locations else {
        return (
            Vec::new(),
            Some("a .json workspace has no source locations".to_string()),
        );
    };
    let plain = |location: Option<&SourceLocation>| -> Vec<Place> {
        location
            .map(|l| Place {
                location: l.clone(),
                note: None,
            })
            .into_iter()
            .collect()
    };
    let places = match target {
        Target::Element { id, .. } => plain(locations.get(id)),
        Target::Port { port_id, .. } => plain(locations.get(port_id)),
        Target::Relationship(r) => relationship_places(r, locations),
        Target::Implied { via, .. } => via
            .iter()
            .flat_map(|r| {
                relationship_places(r, locations)
                    .into_iter()
                    .map(move |mut place| {
                        place.note = Some(format!("implied by {}", describe(r)));
                        place
                    })
            })
            .collect(),
        Target::View { key } => plain(locations.view(key)),
        Target::Decision { id, element_id, .. } => {
            plain(locations.decision(id, element_id.as_deref()))
        }
    };
    if !places.is_empty() {
        return (places, None);
    }
    let note = match target {
        Target::View { key } if generated.contains(key) => {
            "generated by `auto`; no statement declares it"
        }
        _ => "no source location",
    };
    (places, Some(note.to_string()))
}

/// A relationship's own statement, or for one replicated onto deployment
/// instances, the statement of the relationship it copies.
fn relationship_places(r: &RelationshipMatch, locations: &SourceLocations) -> Vec<Place> {
    if let Some(location) = locations.get(&r.id) {
        return vec![Place {
            location: location.clone(),
            note: None,
        }];
    }
    r.linked_relationship_id
        .as_deref()
        .and_then(|id| locations.get(id))
        .map(|location| Place {
            location: location.clone(),
            note: Some("replicated onto deployment instances from".to_string()),
        })
        .into_iter()
        .collect()
}

pub fn describe(r: &RelationshipMatch) -> String {
    match &r.description {
        Some(d) => format!("{} -> {} \"{}\"", r.from, r.to, d),
        None => format!("{} -> {}", r.from, r.to),
    }
}

pub fn label(target: &Target) -> String {
    match target {
        Target::Element { path, .. } | Target::Port { path, .. } => path.clone(),
        Target::Relationship(r) => describe(r),
        Target::Implied { from, to, .. } => format!("{from} -> {to}"),
        Target::View { key } => key.clone(),
        Target::Decision { id, title, .. } => format!("{id}. {title}"),
    }
}

fn target_json(target: &Target) -> Value {
    let mut v = json!({ "kind": target.kind(), "label": label(target) });
    match target {
        Target::Element { id, path, .. } => {
            v["id"] = json!(id);
            v["path"] = json!(path);
        }
        Target::Port {
            element_id,
            port_id,
            path,
        } => {
            v["id"] = json!(port_id);
            v["elementId"] = json!(element_id);
            v["path"] = json!(path);
        }
        Target::Relationship(r) => {
            v["id"] = json!(r.id);
            v["from"] = json!(r.from);
            v["to"] = json!(r.to);
            v["description"] = json!(r.description);
        }
        Target::Implied { from, to, via } => {
            v["from"] = json!(from);
            v["to"] = json!(to);
            v["via"] = json!(via.iter().map(|r| &r.id).collect::<Vec<_>>());
        }
        Target::View { key } => v["key"] = json!(key),
        Target::Decision { id, element_id, .. } => {
            v["id"] = json!(id);
            v["elementId"] = json!(element_id);
        }
    }
    v
}

fn place_json(place: &Place, sources: &mut SourceLines) -> Value {
    let loc = &place.location;
    json!({
        "file": display_file(loc),
        // For editor links (`vscode://file/<absolutePath>:<line>:<col>`).
        "absolutePath": loc.file.as_deref()
            .and_then(|f| std::fs::canonicalize(f).ok())
            .map(|p| p.display().to_string()),
        "line": loc.line,
        "col": loc.col,
        "endLine": loc.end_line,
        "source": loc.file.as_deref().and_then(|f| sources.line(f, loc.line)),
        "note": place.note,
    })
}

pub fn display_file(loc: &SourceLocation) -> String {
    loc.file
        .as_deref()
        .map_or_else(|| "<input>".to_string(), |f| f.display().to_string())
}

pub fn miss_message(miss: &Miss) -> String {
    match miss.kind {
        MissKind::Element => format!("no element or port with path '{}'", miss.name),
        MissKind::Relationship if miss.candidates.is_empty() => {
            format!("no relationship, declared or implied, for '{}'", miss.name)
        }
        MissKind::Relationship => format!(
            "no relationship described '{}' between those ends",
            miss.name
        ),
        MissKind::View => format!("no view with key '{}'", miss.name),
        MissKind::Decision => format!("no decision with id '{}'", miss.name),
    }
}

/// The closest candidate to what was not found; failing that, for a path, one
/// with the same last segment — the element moved to a different parent.
pub fn suggestion(miss: &Miss) -> Option<String> {
    structurizr_dsl::suggest::closest(&miss.name, miss.candidates.iter().map(String::as_str))
        .or_else(|| {
            if miss.kind != MissKind::Element {
                return None;
            }
            let last = miss.name.rsplit('/').next()?;
            miss.candidates
                .iter()
                .find(|c| {
                    c.rsplit('/')
                        .next()
                        .is_some_and(|l| l.eq_ignore_ascii_case(last))
                })
                .cloned()
        })
}

/// Source files read on demand, for echoing a statement's first line.
#[derive(Default)]
pub struct SourceLines {
    files: HashMap<PathBuf, Option<Vec<String>>>,
}

impl SourceLines {
    pub fn line(&mut self, file: &Path, line: usize) -> Option<String> {
        let lines = self.files.entry(file.to_path_buf()).or_insert_with(|| {
            std::fs::read_to_string(file)
                .ok()
                .map(|s| s.lines().map(str::to_string).collect())
        });
        lines
            .as_ref()?
            .get(line.checked_sub(1)?)
            .map(|l| l.trim().to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn json_carries_absolute_paths_for_editor_links() {
        let dir = std::env::temp_dir().join(format!("sx-web-locate-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let file = dir.join("ws.dsl");
        std::fs::write(
            &file,
            "workspace {\n  model {\n    shop = softwareSystem \"Shop\"\n  }\n}\n",
        )
        .unwrap();

        let parsed = structurizr_dsl::parse_file_detailed(&file).unwrap();
        let catalog = Catalog::new(&parsed.workspace);
        let references = ["Shop".to_string(), "Nope".to_string()];
        let json = to_json(&locate(
            &catalog,
            Some(&parsed.locations),
            &HashSet::new(),
            &references,
        ));

        let place = &json["items"][0]["locations"][0];
        assert_eq!(place["line"], 3);
        assert_eq!(place["source"], "shop = softwareSystem \"Shop\"");
        let absolute = place["absolutePath"].as_str().unwrap();
        assert!(
            Path::new(absolute).is_absolute() && absolute.ends_with("ws.dsl"),
            "{absolute}"
        );
        assert_eq!(json["unresolved"][0]["reference"], "Nope");
        std::fs::remove_dir_all(&dir).ok();
    }
}
