//! Where in the DSL source each model element and relationship was declared.
//!
//! Built by [`crate::parse_file_detailed`] / [`crate::parse_str_detailed`] so
//! tooling (the `locate` command, the LSP) can point from a model id, view key
//! or decision back to the text that produced it, across `!include`d files.

use std::collections::HashMap;
use std::path::PathBuf;

use structurizr_model::Workspace;

use crate::identifier_register::IdentifierRegister;
use crate::lexer::{Spanned, Token};

/// The source span of one declaration statement.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SourceLocation {
    /// File the statement is in: the entry file or an `!include`d one, as a
    /// path joined onto the entry file's directory. `None` when parsing a
    /// string rather than a file.
    pub file: Option<PathBuf>,
    /// 1-based line of the statement's first token (an `ident =` prefix
    /// included).
    pub line: usize,
    /// 1-based column of that token.
    pub col: usize,
    /// 1-based line the statement ends on: its closing `}` for a block,
    /// otherwise its last token.
    pub end_line: usize,
}

/// Declaration locations of model elements, ports and relationships (by id),
/// views (by key) and imported decisions (by id and owning element). Ids the
/// parser synthesizes rather than reads — relationships replicated onto
/// deployment instances — have no entry; follow their
/// `linked_relationship_id` instead.
#[derive(Debug, Clone, Default)]
pub struct SourceLocations {
    by_id: HashMap<String, SourceLocation>,
    views: HashMap<String, SourceLocation>,
    /// (decision id, owning element id, location). Decision ids are only
    /// unique per owner: each `!adrs` directory numbers from 1.
    decisions: Vec<(String, Option<String>, SourceLocation)>,
}

impl SourceLocations {
    pub fn get(&self, id: &str) -> Option<&SourceLocation> {
        self.by_id.get(id)
    }

    pub fn len(&self) -> usize {
        self.by_id.len()
    }

    pub fn is_empty(&self) -> bool {
        self.by_id.is_empty()
    }

    /// Every located model id (elements, ports, relationships), unordered.
    pub fn iter(&self) -> impl Iterator<Item = (&str, &SourceLocation)> {
        self.by_id.iter().map(|(id, location)| (id.as_str(), location))
    }

    /// Every view declared with an explicit key, unordered.
    pub fn views(&self) -> impl Iterator<Item = (&str, &SourceLocation)> {
        self.views.iter().map(|(key, location)| (key.as_str(), location))
    }

    /// The statement declaring the view with `key`. Views without an explicit
    /// key, and views generated by `auto`, have none.
    pub fn view(&self, key: &str) -> Option<&SourceLocation> {
        self.views.get(key)
    }

    /// The Markdown file decision `id` was imported from: the whole file,
    /// since the decision is the file.
    pub fn decision(&self, id: &str, element_id: Option<&str>) -> Option<&SourceLocation> {
        self.decisions
            .iter()
            .find(|(d, owner, _)| d == id && owner.as_deref() == element_id)
            .map(|(_, _, location)| location)
    }

    pub(crate) fn insert(&mut self, id: String, location: SourceLocation) {
        self.by_id.insert(id, location);
    }

    pub(crate) fn insert_view(&mut self, key: String, location: SourceLocation) {
        self.views.insert(key, location);
    }

    pub(crate) fn push_decision(&mut self, id: String, element_id: Option<String>, location: SourceLocation) {
        self.decisions.push((id, element_id, location));
    }
}

/// Everything a detailed parse produces.
#[derive(Debug, Clone)]
pub struct Parsed {
    pub workspace: Workspace,
    pub identifiers: IdentifierRegister,
    pub locations: SourceLocations,
}

/// Index of the first token of the statement containing `anchor`: walk back
/// along the line, stopping at a brace so a one-line nested block
/// (`s = softwareSystem "S" { c = container "C" }`) yields `c`, not `s`.
pub(crate) fn statement_start(tokens: &[Spanned], anchor: usize) -> usize {
    let mut i = anchor.min(tokens.len().saturating_sub(1));
    while i > 0 {
        let prev = &tokens[i - 1];
        if prev.pos.line != tokens[i].pos.line
            || matches!(prev.token, Token::OpenBrace | Token::CloseBrace)
        {
            break;
        }
        i -= 1;
    }
    i
}

/// Spliced line the statement starting at `start` ends on: the end of its
/// line, or the brace closing a block opened on it. A statement whose last
/// token is a multi-line text block reports the block's first line, since
/// tokens only carry a start position.
pub(crate) fn statement_end_line(tokens: &[Spanned], start: usize) -> usize {
    let mut depth = 0usize;
    let mut last = start;
    for (j, t) in tokens.iter().enumerate().skip(start + 1) {
        if depth == 0 && t.pos.line != tokens[last].pos.line {
            break;
        }
        match t.token {
            Token::OpenBrace => depth += 1,
            Token::CloseBrace if depth == 0 => break,
            Token::CloseBrace => depth -= 1,
            _ => {}
        }
        last = j;
    }
    tokens[last].pos.line
}
